language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install nose coverage
  - pip install -U codecov
script: nosetests tests --with-coverage --cover-package=silkyy --cover-html
after_success:
  - codecov
services:
  - redis-server